name: node.js CI

on:
 push:
   branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
      - uses: docker/setup-buildx-actions@v2

      - name: login to DockerHub
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          paasword: ${{ secrets.DOCKER_PASSWORD }}

       -name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: arif346/devops-node-app:latest 
